### ISSUE TITLE
End of typing event

### ISSUE THREAD

**Issue by carnivash** [antoniocapelo/angular-typewrite#13]
Is there a way to fire an event when the text finished typing?

**Comment by antoniocapelo** [comment]
@carnivash yes, it's mentioned in the doc:

**scope callback**: pass the desired scope callback as the 'callback-fn' attribute of the element

this callback will be fired once the typing ends.

Please tell me if it's resolved so I can close the issue

**Comment by carnivash** [comment]
Yes, that's it, thanks.
