### ISSUE TITLE
How to make loop/clear

### ISSUE THREAD

**Issue by Arth95** [antoniocapelo/angular-typewrite#3]
Hi!

Youre directive is pretty awesome, but I don't know how to erease text or loop it.
You said in previous issue that you added this feature. Is it in docs?

**Comment by kieszistvan** [comment]
Check https://github.com/kieszistvan/angular-typewrite. I added a loop attribute to the directive, set it to true and see if it works or not. TBH I added it "blindly" to the code so please let me know if it fails :) If it works I create the pull request.

**Comment by antoniocapelo** [comment]
@Arth95 I've yet to add the 'looping' feature, however the erase one is mentioned in the docs:

"The 'text' attribute can be a single string or an array of string. In case an array is passed, the string on each index is erased so the next item can be printed. When the last index is reached, that string stays on the screen. (So if you want to erase the last string, just push an empty string to the end of the array)."

Let me know if it works ok

**Comment by FindBoat** [comment]
Does the loop feature actually work? How can I enable it?
