### ISSUE TITLE
bower dependency on angular ~1.2.0

### ISSUE THREAD

**Issue by episodeyang** [antoniocapelo/angular-typewrite#4]
is this a hard dependency? We could bump it up since 1.3.16 and 1.4 are widely in use now.

**Comment by antoniocapelo** [comment]
@episodeyang it is not, it's a minimum dependency so yes we can bump it or make it a weak dependency :) I'll take a look as soon as I have time

**Comment by inexuscore** [comment]
waiting for a bower update.
angular 1.5+ is out in the open, thank you for the repo thou, awesomeness :godmode:

**Comment by antoniocapelo** [comment]
@inexuscore got lost in the middle of stuff. Will look into updating the bower dependency version. Thanks :)

**Comment by inexuscore** [comment]
@antoniocapelo Thank you! :tada:

**Comment by antoniocapelo** [comment]
@inexuscore [just set](https://github.com/antoniocapelo/angular-typewrite/releases) the angular version of 1.2 as minimum dependency as there may be people using it. 

Took the opportunity to retouch some grunt tasks and example of usage.
Will close the issue now :)
